name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- uses: nrwl/nx-set-shas@v2

      - name: Install (dependencies)
        run: |
          yarn --frozen-lockfile

      - name: Lint
        run: |
          npx nx affected --target=lint

      - name: Build (client & ssr)
        run: |
          npx nx build
          npx nx server

      - name: Install (doctl)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login (container registry)
        run: |
          doctl registry login

      - name: Build (container image)
        run: |
          docker build . --build-arg FOLDER_APP_BUNDLE=dist/apps/personal -t registry.digitalocean.com/${{ secrets.DIGITALOCEAN_CONTAINER_REGISTRY_REPOSITORY }}/app-personal:latest

      - name: Push (container image)
        run: |
          docker push registry.digitalocean.com/${{ secrets.DIGITALOCEAN_CONTAINER_REGISTRY_REPOSITORY }}/app-personal:latest
