name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  CONTAINER_REPOSITORY: ghcr.io/rubenvermeulen/web-app-portfolio

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- uses: nrwl/nx-set-shas@v2

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Lint
        run: |
          npx nx affected --target=lint

      - name: Build client & ssr
        run: |
          npx nx build
          npx nx server

      - name: Login into registry
        run: |
          docker login ghcr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: |
          echo "CONTAINER_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build . --build-arg APP_BUNDLE_PATH=dist/apps/personal -t ${{ env.CONTAINER_REPOSITORY }}:${{ env.CONTAINER_IMAGE_TAG }} -t ${{ env.CONTAINER_REPOSITORY }}:latest

      - name: Push to registry
        run: |
          docker push --all-tags ${{ env.CONTAINER_REPOSITORY }}
