name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  CONTAINER_REGISTRY: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_CONTAINER_REGISTRY_REPOSITORY }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- uses: nrwl/nx-set-shas@v2

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Lint
        run: |
          npx nx affected --target=lint

      - name: Build client & ssr
        run: |
          npx nx build
          npx nx server

      - name: Login into registry
        run: |
          docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com

      - name: Set image tag
        run: |
          echo "CONTAINER_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build . --build-arg APP_BUNDLE_PATH=dist/apps/personal -t ${{ env.CONTAINER_REGISTRY }}/app-personal:${{ env.CONTAINER_IMAGE_TAG }} -t ${{ env.CONTAINER_REGISTRY }}/app-personal:latest

      - name: Push to registry
        run: |
          docker push --all-tags ${{ env.CONTAINER_REGISTRY }}/app-personal

#      - name: Deploy to app platform
#        uses: digitalocean/app_action@main
#        with:
#          app_name: rubenvermeulen-be
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#          images: '[
#                    {
#                      "name": "app-personal",
#                      "image":{
#                        "registry_type": "DOCR",
#                        "repository": "app-personal",
#                        "tag": "${{ env.CONTAINER_IMAGE_TAG }}"
#                      }
#                    }
#                  ]'
