name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- uses: nrwl/nx-set-shas@v2

      - name: Install
        run: yarn --frozen-lockfile

      - name: Lint
        run: npx nx affected --target=lint

      - name: Build (client & ssr)
        run: |
          npx nx build
          npx nx server
          npx nx post-build

      - name: Release
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/apps
